CUDA_VISIBLE_DEVICES=$1 python src/mutual_distill_parallel.py \
	 --device1 0 \
	 --device2 1 \
 	 --batch_size_bi_encoder 128 \
	 --batch_size_cross_encoder 32 \
	 --num_epochs_bi_encoder 10 \
	 --num_epochs_cross_encoder 1 \
	 --cycle 3 \
	 --bi_encoder1_pooling_mode cls \
	 --bi_encoder2_pooling_mode cls \
	 --init_with_new_models \
	 --task sts_sickr \
	 --random_seed 2021 